site_name: Dyglot Documentation
site_url: https://dyglot-doc.canardoux.xyz

repo_url: https://github.com/canardoux/dyglot
repo_name: canardoux/dyglot

theme:
  name: material
  language: en
  features:
    - navigation.footer
    - navigation.top

nav:
  - Introduction: 
      - Overview: introduction/index.md
      - Architecture at a Glance: introduction/architecture-at-a-glance.md
      - Vision: introduction/vision-architecture.md
      - Glossary: introduction/glossary.md
      - FAQ: introduction/faq.md

  - Student:
      - Overview: student/index.md
      - Getting Started: student/getting-started.md
      - First Launch & Discovery Flow: student/discovery.md
      - Home: student/home.md
      - Practice: student/practice.md
      - Practice Engines: student/engine.md
      - Session: student/session.md
      - Session et Progress Model: student/progress.md
      - Course (classroom): student/course.md
      - Views: student/view.md
      - Filters: student/filter.md
      - Expert: student/expert.md
      - FAQ: student/faq.md
 
  - Teacher:
      - Overview: teacher/index.md
      - classroom: teacher/classroom.md
      - CardSet vs Course: teacher/cardset-vs-course.md
      - Filter: teacher/filter.md
      - Content Model: teacher/content-model.md
      - Publishing: teacher/publishing.md
      - Views: teacher/view.md
      - Screen Design: teacher/screen.md
      - Live Preview: teacher/live-preview.md
      - License: teacher/license.md
      - FAQ: teacher/faq.md
 
  - Engine:
      - Overview: engine/index.md
      - Studio: engine/studio.md
      - Live Preview: engine/preview.md
      - View Rendering: engine/rendering.md
      - License: engine/license.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
